# Generated by Django 5.1.5 on 2025-04-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspectionticket_inspection_notes'),
        ('warranty', '0003_remove_policy_email_remove_policy_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionticket',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warranty.claim'),
        ),
    ]
