# Generated by Django 5.1.5 on 2025-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('warranty_type', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('date_issued', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=100)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('dealership_notes', models.TextField(blank=True, null=True)),
                ('estimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c3_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('policy_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
