# Generated by Django 5.1.5 on 2025-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='initiated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='warranty_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
