# Generated by Django 5.2 on 2025-04-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_claim_first_name_claim_initiated_by_claim_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='phone',
        ),
    ]
